<#ftl strip_whitespace="true">
<#assign importList = [] />
package org.genevaers.repository.components;

<#--- Get a list of unique enum entries to be imported --->
<#list component.members as member>
    <#if member.importString ?? && ! importList?seq_contains(member.importString)>
        <#assign importList = importList + [member.importString] />
    </#if>
</#list>
<#list importList?sort as i>
${i}
</#list>

/**
 * This class was automatically generated by the GenevaERS Component Generator.
 * 
 * DO NOT EDIT
 * 
 */
public class ${component.componentName} extends ComponentNode
{
<#list component.members as member>
${member.fieldEntry}
</#list>

<#list component.members as member>
${member.getAndSetEntry}
</#list>
}
