<#ftl strip_whitespace="true">
**********************************************************************
*
* This files was automatically generated by the GenevaERS Component Generator.
* 
* DO NOT EDIT
* 
* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
*

<#list enumEntires.enums as vals>
*** ${vals.description}
<#list vals.equates as e>
<#assign name = vals.asmPrefix + e>
${name?right_pad(42)} EQU X'${e?index?c?left_pad(2, '0')}'
</#list>

</#list>
