HIDE_GENERATION=Y
HIDE_LKLR_VALUES=Y
*HIDE_WRITE_SUFFIX=N
*REPLACE_0_POS=N
HIDE_JOIN_NUMBER=Y
HIDE_SOURCE_LF=N
[DEFAULT]
IN_LOGIC_TABLE.FILE=${infile}
RPT.FILE=${rpt}
HIDE_LOOKUP_FIELDS=Y
SEPARATE_SOURCES=N
JLT_SUMMARY=Y

