HIDE_GENERATION=Y
HIDE_LKLR_VALUES=Y
*HIDE_WRITE_SUFFIX=N
*REPLACE_0_POS=N
HIDE_JOIN_NUMBER=N
HIDE_SOURCE_LF=N
HIDE_LOOKUP_FIELD_IDS=N
[DEFAULT]
IN_LOGIC_TABLE.FILE=${infile}
RPT.FILE=${rpt}
*SEPARATE_SOURCES=Y

